project:
  type: website
  output-dir: docs

website:
  title: "Kananioaloha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: projects
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/Kananioaloha/Kananioaloha.github.io

format:
  html:
    theme: minty
    css: styles.css
    toc: false

editor: visual

